name: json_api_common
version: 0.0.4
homepage: https://github.com/f3ath/json-api-common
description: JSON:API for Dart. Common parts. See http://jsonapi.org
environment:
  sdk: '>=2.10.0 <3.0.0'
dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4
  test_coverage: ^0.4.3

