name: json_api_common
version: 0.1.0-nullsafety
homepage: https://github.com/f3ath/json-api-common
description: JSON:API for Dart. Common parts. See http://jsonapi.org
environment:
  sdk: '>=2.10.0-dev <3.0.0'
dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety.2

