name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linter:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Linter
      run: dartanalyzer --fatal-infos --fatal-warnings lib test
      
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [latest, '2.8']
        platform: ['vm', 'chrome', 'firefox']
    container:
      image:  google/dart:${{ matrix.version }}
    steps:
    - uses: actions/checkout@v2
    - name: Install Browsers
      run: sudo apt install chrome firefox  
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test --platform ${{ matrix.platform }}
