name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [latest, '2.8']
        platform: ['vm', 'chrome']
    container:
      image:  google/dart:${{ matrix.version }}
    steps:
    - uses: actions/checkout@v2
    - run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - run: sudo dpkg -i google-chrome*.deb
    - name: Install dependencies
      run: pub get
    - name: Linter
      run: dartanalyzer --fatal-infos --fatal-warnings lib test
    - name: Tests
      run: pub run test --platform ${{ matrix.platform }}
