name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - name: Install dart
      run: apt-get install dart
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Linter
      run: dartanalyzer --fatal-infos --fatal-warnings lib test
      
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ['vm', 'chrome', 'firefox']
    steps:
    - name: Install dart
      run: apt-get install dart
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test --platform ${{ matrix.platform }}
